//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReciboPago
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://modificacion.recibos.sittegws/", ConfigurationName="ReciboPago.RecibosPagoWS")]
    public interface RecibosPagoWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://modificacion.recibos.sittegws/RecibosPagoWS/reversaDePagoRequest", ReplyAction="http://modificacion.recibos.sittegws/RecibosPagoWS/reversaDePagoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ReciboPago.reversaDePagoResponse> reversaDePagoAsync(ReciboPago.reversaDePagoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://modificacion.recibos.sittegws/")]
    public partial class respuestaObj
    {
        
        private int codigoRespuestaField;
        
        private bool codigoRespuestaFieldSpecified;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoRespuestaSpecified
        {
            get
            {
                return this.codigoRespuestaFieldSpecified;
            }
            set
            {
                this.codigoRespuestaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reversaDePago", WrapperNamespace="http://modificacion.recibos.sittegws/", IsWrapped=true)]
    public partial class reversaDePagoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.recibos.sittegws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UsuarioLog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.recibos.sittegws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PasswordLog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.recibos.sittegws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReciboControlInterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.recibos.sittegws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaReversa;
        
        public reversaDePagoRequest()
        {
        }
        
        public reversaDePagoRequest(string UsuarioLog, string PasswordLog, string ReciboControlInterno, string FechaReversa)
        {
            this.UsuarioLog = UsuarioLog;
            this.PasswordLog = PasswordLog;
            this.ReciboControlInterno = ReciboControlInterno;
            this.FechaReversa = FechaReversa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reversaDePagoResponse", WrapperNamespace="http://modificacion.recibos.sittegws/", IsWrapped=true)]
    public partial class reversaDePagoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.recibos.sittegws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ReciboPago.respuestaObj @return;
        
        public reversaDePagoResponse()
        {
        }
        
        public reversaDePagoResponse(ReciboPago.respuestaObj @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface RecibosPagoWSChannel : ReciboPago.RecibosPagoWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class RecibosPagoWSClient : System.ServiceModel.ClientBase<ReciboPago.RecibosPagoWS>, ReciboPago.RecibosPagoWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RecibosPagoWSClient() : 
                base(RecibosPagoWSClient.GetDefaultBinding(), RecibosPagoWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RecibosPagoWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecibosPagoWSClient(EndpointConfiguration endpointConfiguration) : 
                base(RecibosPagoWSClient.GetBindingForEndpoint(endpointConfiguration), RecibosPagoWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecibosPagoWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RecibosPagoWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecibosPagoWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RecibosPagoWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecibosPagoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ReciboPago.reversaDePagoResponse> reversaDePagoAsync(ReciboPago.reversaDePagoRequest request)
        {
            return base.Channel.reversaDePagoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RecibosPagoWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RecibosPagoWS))
            {
                return new System.ServiceModel.EndpointAddress("http://spenlinea.guanajuato.gob.mx:8080/SittegWS/RecibosPagoWS");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RecibosPagoWSClient.GetBindingForEndpoint(EndpointConfiguration.RecibosPagoWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RecibosPagoWSClient.GetEndpointAddress(EndpointConfiguration.RecibosPagoWS);
        }
        
        public enum EndpointConfiguration
        {
            
            RecibosPagoWS,
        }
    }
}
