//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfraccionPagoServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://modificacion.infracciones.sittegws/", ConfigurationName="InfraccionPagoServiceReference.InfraccionPagoWS")]
    public interface InfraccionPagoWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://modificacion.infracciones.sittegws/InfraccionPagoWS/registrarPagoInfraccio" +
            "nRequest", ReplyAction="http://modificacion.infracciones.sittegws/InfraccionPagoWS/registrarPagoInfraccio" +
            "nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<InfraccionPagoServiceReference.registrarPagoInfraccionResponse> registrarPagoInfraccionAsync(InfraccionPagoServiceReference.registrarPagoInfraccionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://modificacion.infracciones.sittegws/")]
    public partial class datosInfraccion
    {
        
        private string anioFiscalField;
        
        private string claveAplicFinField;
        
        private string claveGarantiaFinField;
        
        private int codigoRespuestaField;
        
        private bool codigoRespuestaFieldSpecified;
        
        private string cveDependenciaField;
        
        private long cveEstatusInfrField;
        
        private bool cveEstatusInfrFieldSpecified;
        
        private string cveMunicipioField;
        
        private string cveOficinaField;
        
        private string cveOficinaEnvioField;
        
        private string delegacionField;
        
        private string domicilioPropOInfrField;
        
        private string estatusInfrField;
        
        private string fechaInfraccionField;
        
        private string fechaNotificadoField;
        
        private string fechaOficioEnvioField;
        
        private string fechaPagoField;
        
        private string fechaVencimientoField;
        
        private string folioField;
        
        private string garantiaField;
        
        private string horaField;
        
        private string identificadorField;
        
        private string lugarField;
        
        private string lugarPagoIDField;
        
        private string marcaField;
        
        private string mensajeField;
        
        private string montoField;
        
        private string montoPagadoField;
        
        private string montoSinDescuentoField;
        
        private string municipioField;
        
        private string nombreField;
        
        private string oficioEnvioField;
        
        private string oficioEnvioAutoridadField;
        
        private string placasField;
        
        private string reciboControlInternoField;
        
        private string rfcPropOInfractorField;
        
        private string submarcaField;
        
        private string tipoAplicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string anioFiscal
        {
            get
            {
                return this.anioFiscalField;
            }
            set
            {
                this.anioFiscalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string claveAplicFin
        {
            get
            {
                return this.claveAplicFinField;
            }
            set
            {
                this.claveAplicFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string claveGarantiaFin
        {
            get
            {
                return this.claveGarantiaFinField;
            }
            set
            {
                this.claveGarantiaFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoRespuesta
        {
            get
            {
                return this.codigoRespuestaField;
            }
            set
            {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoRespuestaSpecified
        {
            get
            {
                return this.codigoRespuestaFieldSpecified;
            }
            set
            {
                this.codigoRespuestaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cveDependencia
        {
            get
            {
                return this.cveDependenciaField;
            }
            set
            {
                this.cveDependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long cveEstatusInfr
        {
            get
            {
                return this.cveEstatusInfrField;
            }
            set
            {
                this.cveEstatusInfrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cveEstatusInfrSpecified
        {
            get
            {
                return this.cveEstatusInfrFieldSpecified;
            }
            set
            {
                this.cveEstatusInfrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string cveMunicipio
        {
            get
            {
                return this.cveMunicipioField;
            }
            set
            {
                this.cveMunicipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string cveOficina
        {
            get
            {
                return this.cveOficinaField;
            }
            set
            {
                this.cveOficinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string cveOficinaEnvio
        {
            get
            {
                return this.cveOficinaEnvioField;
            }
            set
            {
                this.cveOficinaEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string delegacion
        {
            get
            {
                return this.delegacionField;
            }
            set
            {
                this.delegacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string domicilioPropOInfr
        {
            get
            {
                return this.domicilioPropOInfrField;
            }
            set
            {
                this.domicilioPropOInfrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string estatusInfr
        {
            get
            {
                return this.estatusInfrField;
            }
            set
            {
                this.estatusInfrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string fechaInfraccion
        {
            get
            {
                return this.fechaInfraccionField;
            }
            set
            {
                this.fechaInfraccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string fechaNotificado
        {
            get
            {
                return this.fechaNotificadoField;
            }
            set
            {
                this.fechaNotificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string fechaOficioEnvio
        {
            get
            {
                return this.fechaOficioEnvioField;
            }
            set
            {
                this.fechaOficioEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string fechaPago
        {
            get
            {
                return this.fechaPagoField;
            }
            set
            {
                this.fechaPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string fechaVencimiento
        {
            get
            {
                return this.fechaVencimientoField;
            }
            set
            {
                this.fechaVencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string folio
        {
            get
            {
                return this.folioField;
            }
            set
            {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string garantia
        {
            get
            {
                return this.garantiaField;
            }
            set
            {
                this.garantiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string hora
        {
            get
            {
                return this.horaField;
            }
            set
            {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string lugar
        {
            get
            {
                return this.lugarField;
            }
            set
            {
                this.lugarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string lugarPagoID
        {
            get
            {
                return this.lugarPagoIDField;
            }
            set
            {
                this.lugarPagoIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string marca
        {
            get
            {
                return this.marcaField;
            }
            set
            {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string monto
        {
            get
            {
                return this.montoField;
            }
            set
            {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string montoPagado
        {
            get
            {
                return this.montoPagadoField;
            }
            set
            {
                this.montoPagadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string montoSinDescuento
        {
            get
            {
                return this.montoSinDescuentoField;
            }
            set
            {
                this.montoSinDescuentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string municipio
        {
            get
            {
                return this.municipioField;
            }
            set
            {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string oficioEnvio
        {
            get
            {
                return this.oficioEnvioField;
            }
            set
            {
                this.oficioEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string oficioEnvioAutoridad
        {
            get
            {
                return this.oficioEnvioAutoridadField;
            }
            set
            {
                this.oficioEnvioAutoridadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string placas
        {
            get
            {
                return this.placasField;
            }
            set
            {
                this.placasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string reciboControlInterno
        {
            get
            {
                return this.reciboControlInternoField;
            }
            set
            {
                this.reciboControlInternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string rfcPropOInfractor
        {
            get
            {
                return this.rfcPropOInfractorField;
            }
            set
            {
                this.rfcPropOInfractorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string submarca
        {
            get
            {
                return this.submarcaField;
            }
            set
            {
                this.submarcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string tipoAplicacion
        {
            get
            {
                return this.tipoAplicacionField;
            }
            set
            {
                this.tipoAplicacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarPagoInfraccion", WrapperNamespace="http://modificacion.infracciones.sittegws/", IsWrapped=true)]
    public partial class registrarPagoInfraccionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.infracciones.sittegws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UsuarioLog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.infracciones.sittegws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PasswordLog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.infracciones.sittegws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FolioInfraccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.infracciones.sittegws/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MotoPagado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.infracciones.sittegws/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaPago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.infracciones.sittegws/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReciboControlInterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.infracciones.sittegws/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LugarPagoID;
        
        public registrarPagoInfraccionRequest()
        {
        }
        
        public registrarPagoInfraccionRequest(string UsuarioLog, string PasswordLog, string FolioInfraccion, string MotoPagado, string FechaPago, string ReciboControlInterno, string LugarPagoID)
        {
            this.UsuarioLog = UsuarioLog;
            this.PasswordLog = PasswordLog;
            this.FolioInfraccion = FolioInfraccion;
            this.MotoPagado = MotoPagado;
            this.FechaPago = FechaPago;
            this.ReciboControlInterno = ReciboControlInterno;
            this.LugarPagoID = LugarPagoID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarPagoInfraccionResponse", WrapperNamespace="http://modificacion.infracciones.sittegws/", IsWrapped=true)]
    public partial class registrarPagoInfraccionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://modificacion.infracciones.sittegws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public InfraccionPagoServiceReference.datosInfraccion @return;
        
        public registrarPagoInfraccionResponse()
        {
        }
        
        public registrarPagoInfraccionResponse(InfraccionPagoServiceReference.datosInfraccion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface InfraccionPagoWSChannel : InfraccionPagoServiceReference.InfraccionPagoWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class InfraccionPagoWSClient : System.ServiceModel.ClientBase<InfraccionPagoServiceReference.InfraccionPagoWS>, InfraccionPagoServiceReference.InfraccionPagoWS
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public InfraccionPagoWSClient() : 
                base(InfraccionPagoWSClient.GetDefaultBinding(), InfraccionPagoWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.InfraccionPagoWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InfraccionPagoWSClient(EndpointConfiguration endpointConfiguration) : 
                base(InfraccionPagoWSClient.GetBindingForEndpoint(endpointConfiguration), InfraccionPagoWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InfraccionPagoWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(InfraccionPagoWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InfraccionPagoWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(InfraccionPagoWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public InfraccionPagoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<InfraccionPagoServiceReference.registrarPagoInfraccionResponse> InfraccionPagoServiceReference.InfraccionPagoWS.registrarPagoInfraccionAsync(InfraccionPagoServiceReference.registrarPagoInfraccionRequest request)
        {
            return base.Channel.registrarPagoInfraccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<InfraccionPagoServiceReference.registrarPagoInfraccionResponse> registrarPagoInfraccionAsync(string UsuarioLog, string PasswordLog, string FolioInfraccion, string MotoPagado, string FechaPago, string ReciboControlInterno, string LugarPagoID)
        {
            InfraccionPagoServiceReference.registrarPagoInfraccionRequest inValue = new InfraccionPagoServiceReference.registrarPagoInfraccionRequest();
            inValue.UsuarioLog = UsuarioLog;
            inValue.PasswordLog = PasswordLog;
            inValue.FolioInfraccion = FolioInfraccion;
            inValue.MotoPagado = MotoPagado;
            inValue.FechaPago = FechaPago;
            inValue.ReciboControlInterno = ReciboControlInterno;
            inValue.LugarPagoID = LugarPagoID;
            return ((InfraccionPagoServiceReference.InfraccionPagoWS)(this)).registrarPagoInfraccionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InfraccionPagoWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.InfraccionPagoWS))
            {
                return new System.ServiceModel.EndpointAddress("http://spenlinea.guanajuato.gob.mx:8080/SittegWS/InfraccionPagoWS");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return InfraccionPagoWSClient.GetBindingForEndpoint(EndpointConfiguration.InfraccionPagoWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return InfraccionPagoWSClient.GetEndpointAddress(EndpointConfiguration.InfraccionPagoWS);
        }
        
        public enum EndpointConfiguration
        {
            
            InfraccionPagoWS,
        }
    }
}
